### ISSUE TITLE
可以检测是否有自己的数字水印吗

### ISSUE THREAD

**Issue by z411500976** [zy445566/node-digital-watermarking#10]
可以代码实现检测是否有自己的数字水印吗   比如说检测图片是不是我们的图片   而不用导出来才能识别

**Comment by zy445566** [comment]
理论上解密图片后，使用文字提取识别图片文字是可行的，但是加密图经给裁剪和模糊化之后，文字提取则会更加模糊。
所以我认为这不是这个库的开发范围，近期也没有这个需求。如果你需要，可以往文字提前这方面做
