### ISSUE TITLE
有计划支持web么？

### ISSUE THREAD

**Issue by ystyle** [zy445566/node-digital-watermarking#11]
有计划支持web么？

**Comment by zy445566** [comment]
嗯，明天搞下看看

**Comment by ystyle** [comment]
哇，回复好快， 那先谢谢啦

**Comment by zy445566** [comment]
> 哇，回复好快， 那先谢谢啦

但这个是基于opencv搞的，大概有7M，你确定还想要吗？

**Comment by ystyle** [comment]
应该没问题

**Comment by zy445566** [comment]
> 应该没问题

新开了个仓库搞这个：

https://github.com/zy445566/web-digital-watermarking

你可以先试试   npm install web-digital-watermarking

**Comment by zy445566** [comment]
那issue关闭了，如果是web-digital-watermarking的问题在https://github.com/zy445566/web-digital-watermarking/issue 提吧
