### ISSUE TITLE
报错： UnhandledPromiseRejectionWarning: Error: Cannot find module './opencv.js'

### ISSUE THREAD

**Issue by Rabbitzzc** [zy445566/node-digital-watermarking#12]
![image](https://user-images.githubusercontent.com/26913511/101065494-3135a100-35d0-11eb-9e83-f1117b0d235a.png)

**Comment by Rabbitzzc** [comment]
是我 node 版本过低了，应该至少为 `v12.0.0`

**Comment by zy445566** [comment]
> 是我 node 版本过低了，应该至少为 `v12.0.0`

你确定是因为版本问题吗？

**Comment by Rabbitzzc** [comment]
> > 是我 node 版本过低了，应该至少为 `v12.0.0`
> 
> 你确定是因为版本问题吗？因为版本问题一般不会报文件找不到吧。因为我还是比较好奇是如何复现的

你可以尝试一下，我只是暂时用了，没有继续深究。我用10.x 是不可以的

**Comment by zy445566** [comment]
> 你可以尝试一下，我只是暂时用了，没有继续深究。我用10.x 是不可以的


感谢，我现在找到原因了，之前为了解决内存泄漏使用require-vm这个库，这个库判断父引用是通过module.parent.path,然而node12才有module.parent.path，后来使用了path.dirname(module.parent.filename)来替代module.parent.path，目前我测试node8,node10,node12都可以支持了

**Comment by Rabbitzzc** [comment]
可以可以，很厉害！
