### ISSUE TITLE
加密后的文件体积剧增……

### ISSUE THREAD

**Issue by saint3347** [zy445566/node-digital-watermarking#13]
测试了下加密，加密后的体积增加了10倍+...请问下设计就是这样的么~~~
![image](https://user-images.githubusercontent.com/7347133/104294986-dd857400-54fa-11eb-9482-67c400490e40.png)
![image](https://user-images.githubusercontent.com/7347133/104295014-e70edc00-54fa-11eb-9a0f-f0681fe96dbf.png)

**Comment by zy445566** [comment]
。。。png格式就是未压缩的图片，你都改成png试试

**Comment by zy445566** [comment]
你好，请问你这边只是因为图片格式问题么？如果只是因为图片格式问题，那么这个issue我可能就在今天关闭了
