### ISSUE TITLE
./opencv.js not found when bundled with esbuild

### ISSUE THREAD

**Issue by allanchua101** [zy445566/node-digital-watermarking#19]
Hi,

We think your package is brilliant! However, when we try to bundle the package using `esbuild`, we're getting an error stating that `opencsv.js` file is missing. Can you please advise on how to solve the problem?

**Comment by zy445566** [comment]
step1: download this file:  https://raw.githubusercontent.com/zy445566/node-digital-watermarking/master/opencv.js
step2: npm i digital-watermarking@1.1.15
step3:
```js
// setConfig before used
dw.setConfig({opencvJsPath:path.join(__dirname,'../opencv.js')})
```

**Comment by allanchua101** [comment]
OMG, tnx for the update! The change worked like magic 😂
