### ISSUE TITLE
关于在抵抗破坏方面的表现

### ISSUE THREAD

**Issue by Stevenhuangqian** [zy445566/node-digital-watermarking#4]
希望readme增加一些关于图片在尺寸缩放，大小压缩，添加干扰(文字，线条)下的提取情况

**Comment by TxOne** [comment]
拍照，截图的图片能解密出来吗

**Comment by zy445566** [comment]
@TxOne 
拍照主要看设备是否高清，非高清则容易丢失点位，导致难以识别或识别结果模糊。
截图则分两种一直是相对无损的截图(如QQ的png),还有使用了压缩算法的截图(如微信的jpg)。而一般来说相对无损的截图截图面积超过一半都是能相对清晰显示出来，而使用了压缩算法，比如可能会将图片相似的颜色点位合并成一个点位，则容易丢失一些或覆盖一些点位导致难以识别或识别结果模糊。

其实这点和电影院的流出电影源是很相似的，一般来说流出电影是高清的，则电影厂商很容易识别出是哪个电影院泄露，从而找该电影院索赔。而非高清源比如偷拍，则是难以识别出哪个个电影院泄露，而无法索赔。

**Comment by zy445566** [comment]
@Stevenhuangqian 
一般来说少量的干扰线或干扰文字是无法影响，但往往图片压缩和添加大量噪点对于图像识别影响则较大。
