### ISSUE TITLE
opencv4 报错

### ISSUE THREAD

**Issue by gexiaowei** [zy445566/node-digital-watermarking#5]
../addon.cc:2:33: 致命错误：opencv2/core/core.hpp：没有那个文件或目录

**Comment by gexiaowei** [comment]
`make: Entering directory `/data/static/lab/node_modules/digital-watermarking/build'
  CXX(target) Release/obj.target/addon/addon.o
../addon.cc:2:33: 致命错误：opencv2/core/core.hpp：没有那个文件或目录
 #include <opencv2/core/core.hpp>
                                 ^
编译中断。
make: *** [Release/obj.target/addon/addon.o] 错误 1
make: Leaving directory `/data/static/lab/node_modules/digital-watermarking/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 2.6.32-573.7.1.el6.x86_64
gyp ERR! command "/root/.nvm/versions/node/v10.16.0/bin/node" "/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/static/lab/node_modules/digital-watermarking
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/data/static/lab/package.json'
npm WARN lab No description
npm WARN lab No repository field.
npm WARN lab No README data
npm WARN lab No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1`

**Comment by zy445566** [comment]
使用的opencv的版本不对，当时我应该使用的是2.4的版本，readme上面也是贴的2.4的安装方法
