### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by arielgelbard** [zy445566/node-digital-watermarking#9]
Hi There,

I was trying to call the function `transformImageWithText` in a loop, but if its more than 30 images in the array, it will crash. Here is the example code I used:

```
for (let count = 1; count <= images.length; count++) {
    await dw.transformImageWithText(srcFileName,watermarkText,fontSize,enCodeFileName);
}
```

do you think its a memory cleanup issue? Here is the error message:

`OpenCV Error: Insufficient memory (Failed to allocate 8294400 bytes) in OutOfMemoryError, file /build/master-contrib_docs-lin64/opencv/modules/core/src/alloc.cpp, line 55
`

I wonder if it also gives a performance boost.

Thanks,

Ariel

**Comment by zy445566** [comment]
Thank you for your feedback.

temporary plan: https://github.com/zy445566/node-digital-watermarking/commit/e298c2bbc1084bc881d1be6821a9a93c6ad9e83f
